### PR TITLE
Make use consistent across node/browser

### PR DESCRIPTION
**Pull request by syrusakbary**
This PR does:
* Make wasi-kernel work in a Browser
* Make wasi-kernel work in Node.js
* Moves all pending files to TypeScript (`stubs.js` -> `stubs.ts`, `bindings/workers.js` -> (`bindings/workers/node.ts` + `bindings/workers/browser.ts`)

All this, without requiring to bundle it with rollup, so the development process can be much quicker.

## How to run in a Browser

Running in a browser is super easy, just executing the `dev:browser` script would setup a new server.

```sh
# To install the requirements
npm install
npm run dev:browser
```

Now, visit http://localhost:1234/ and see the browser console log :)

This server will auto-reload with any new changes and having a <300ms reload (as opposed to 3s build times when bundling)

## How to run in Node

This PR improves how it runs in Node, without requiring any bundling at all (via `ts-node`).

```sh
# To install the requirements
npm install
npm run dev:node
```

Note: the `dev:node` script will be the same as running in your shell `ts-node src/kernel/node.ts`.

### CODE REVIEW

**Comment by syrusakbary** [comment]
Note: feel free to close this PR if it's not useful!

It was good for us to experience first hand how usable is wasmer-js (and we did some fixes thanks to that!)

**Comment by corwin-of-amber** [comment]
Hey, cool! Many thanks!
I do like developing without having to bundle, there's definitely some trickery at play here that I want to learn 😄 
I wish this did not require splitting to so many files, but that's a price I'm willing to pay 💵

**Comment by corwin-of-amber** [comment]
Uh-oh, I merged it with my master branch and now I'm getting this cryptic error in Chrome:
```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at process.ts:100
    at process.ts:112
    at Object.parcelRequire.src/kernel/process.ts.events (process.ts:112)
    at newRequire (browser.33bfc648.js:47)
    at localRequire (browser.33bfc648.js:53)
    at Object.parcelRequire.src/kernel/index.ts../process (index.ts:1)
    at newRequire (browser.33bfc648.js:47)
    at localRequire (browser.33bfc648.js:53)
    at Object.parcelRequire.src/kernel/browser.ts.. (browser.ts:1)
    at newRequire (browser.33bfc648.js:47)
```

At `process.ts` lines 100 and 112 all I find is the definition of `BareProcess` which is not even used by the browser module...

https://github.com/corwin-of-amber/wasi-kernel/tree/fastdev-merged

**Comment by corwin-of-amber** [comment]
I have set `"target": "esNext", "module": "esNext"` in my `tsconfig.json`. Is that incompatible with Parcel?

**Comment by corwin-of-amber** [comment]
Ok I managed to fix it in the branch by adding `"browserslist": ["Chrome 78"]` to `package.json` (after following a long issue thread on this matter).

**Comment by corwin-of-amber** [comment]
Merged manually; I reverted to having a single file for `bindings/workers`.
`"target": "es2019"` apparently clashes with `ts-node`. So that piece is broken, but using `parcel --target node` works.

Thanks again! This will prove useful in development I'm sure.

**Comment by syrusakbary** [comment]
Happy to help!

**Pull request closed without merging**
